set up qunit and make first test
FACN1/week5-hibas-angels pull request #4
Opened 2017-03-21 14:24 UTC by mattlub

2017-03-21 15:38 UTC, JWLD commented on tests/front-end/tests.js
> +});
spacing issues in lines 1, 2, 5 and 6

2017-03-21 15:39 UTC, jwld requested changes
spacing issuez

2017-03-21 16:02 UTC, mattlub commented on tests/front-end/tests.js
> +});
bastard

2017-03-22 08:07 UTC, JWLD commented on tests/front-end/tests.js
> +});
<3

2017-03-22 09:36 UTC, jwld requested changes
improve qunit test

2017-03-22 09:36 UTC, JWLD commented on tests/front-end/tests.js
> +  }
why the function?

2017-03-22 09:39 UTC, merged